pull_request_rules:
  - name: backport to release branches
    conditions:
      - base=main
      - label~=^backport/
    actions:
      backport:
        branches:
          - "{{ label.removeprefix('backport/') }}"
